#!/usr/bin/env ruby

$LOAD_PATH << "lib"
$LOAD_PATH << "models"

require 'environment'
Environment.environment = ENV["ENVIRONMENT"] || "production"
$stderr = $stdout

#require 'injury'
#require 'injury_outcome'
#require 'person'

def menu
<<EOS
What do you want to do?
1. Get a .gif
2. Give a .gif
EOS
end

=begin
def record_desired_outcomes_for(person)
  Injury.all.each do |injury|
    puts "What if #{injury.name}?"
    puts "1. Put me out of my misery."
    puts "2. Just a flesh wound. Carry on."
    response = gets.chomp!
    kill_them = (response == "1")
    if kill_them
      puts "We'll kill you if you suffer from #{injury.name}"
    else
      puts "We'll let you linger on if you suffer from #{injury.name}"
    end
    InjuryOutcome.create_for(person, injury, kill_them)
  end
end

def add_person
  puts "Who do you want to add?"
  person_name = gets
  return unless person_name
  person_name.chomp!
  person = Person.new(person_name)
  if person.save
    puts "#{person.name} has been added."
    record_desired_outcomes_for(person)
  else
    puts person.errors
    add_person
  end
end

def add_injury
  puts "What is the injury you want to add?"
  injury_name = gets
  return unless injury_name
  injury_name.chomp!
  injury = Injury.new(injury_name)
  if injury.save
    puts "#{injury_name} has been added."
  else
    puts injury.errors
    add_injury
  end
end
=end

def select_criteria
  puts "What is your first criteria?"
  criteria = gets
  return unless criteria
  criteria.chomp!
  #DB stuff
end

def enter_url
  puts "Enter your url:"
  url = gets
  return unless url
  url.chomp!
  #DB stuff
end

# REPL
# Read - Eval - Print Loop
def get_menu_selection
  puts menu
  input = gets
  return unless input
  input.chomp!
  if input == "1"
    select_criteria
  elsif input == "2"
    enter_url
  else
    puts "'#{input}' is not a valid selection"
    get_menu_selection
  end
end

get_menu_selection
